# Generated by Django 3.1.5 on 2022-05-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('aphorisms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aphorism',
            name='tag',
            field=models.ManyToManyField(to='tags.Tags'),
        ),
    ]
