# Generated by Django 3.1.5 on 2022-05-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aphorisms', '0002_aphorism_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aphorism',
            old_name='tag',
            new_name='tags',
        ),
    ]
