# Generated by Django 3.1.5 on 2022-05-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aphorisms', '0003_auto_20220513_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aphorism',
            old_name='quote',
            new_name='name',
        ),
    ]
