# Generated by Django 3.1.5 on 2022-05-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aphorisms', '0004_auto_20220513_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aphorism',
            old_name='name',
            new_name='text',
        ),
    ]
