# Generated by Django 3.1.5 on 2022-05-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aphorisms', '0003_auto_20220513_1558'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
